name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.14.0

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist

  deploy_pages:
    needs: build
    runs-on: ubuntu-latest
    name: Deploy

    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist

      - name: Deploy to Pages
        run: npx wrangler pages deploy ./dist --project-name=portfolio-v2
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
